apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "k8s-pvc-usage.serviceAccountName" . }}-binding'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-pvc-usage.serviceAccountName" . }}'
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: '{{ include "k8s-pvc-usage.serviceAccountName" . }}'
  apiGroup: rbac.authorization.k8s.io
